# Generated by Django 6.0 on 2025-12-09 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_alter_eventregistration_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='userapp.userprofile'),
        ),
    ]
