# Generated by Django 6.0 on 2025-12-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_alter_eventregistration_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='attended',
            field=models.BooleanField(default=False),
        ),
    ]
