# Generated by Django 6.0 on 2025-12-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_participant_attended'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='attended',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
