# Generated by Django 6.0 on 2025-12-10 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_participant_registration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='registration_date',
        ),
    ]
