# Generated by Django 6.0 on 2025-12-10 04:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_remove_participant_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
