# Generated by Django 6.0 on 2025-12-10 04:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_participant_registered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='registered_at',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
