# Generated by Django 6.0 on 2025-12-10 04:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_alter_participant_registered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='registered_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
