# Generated by Django 6.0 on 2025-12-10 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0015_alter_participant_registered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
