# Generated by Django 6.0 on 2025-12-10 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0016_alter_participant_registered_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='registered_at',
        ),
    ]
