# Generated by Django 6.0 on 2025-12-10 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0018_eventfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5)),
                ('feedback', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='EventFeedback',
        ),
    ]
